#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("zenmc.Resource", IsApplication=true)]

namespace zenmc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int EditText = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditTextError = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FormGroup = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int LoginEmail = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int LoginPassword = 2131034131;
			
			// aapt resource value: 0x7f050040
			public const int XbtnInsert = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int XerrorLog = 2131034178;
			
			// aapt resource value: 0x7f05003c
			public const int XetCity = 2131034172;
			
			// aapt resource value: 0x7f050035
			public const int XetConfirmPassword = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int XetContactName = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int XetContactPhoneNumber = 2131034167;
			
			// aapt resource value: 0x7f05003f
			public const int XetCountry = 2131034175;
			
			// aapt resource value: 0x7f05002d
			public const int XetEmail = 2131034157;
			
			// aapt resource value: 0x7f050032
			public const int XetFemale = 2131034162;
			
			// aapt resource value: 0x7f05002c
			public const int XetFullName = 2131034156;
			
			// aapt resource value: 0x7f050030
			public const int XetGender = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int XetMale = 2131034161;
			
			// aapt resource value: 0x7f050039
			public const int XetMedicalConditions = 2131034169;
			
			// aapt resource value: 0x7f050034
			public const int XetPassword = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int XetPhoneNumber = 2131034163;
			
			// aapt resource value: 0x7f05003a
			public const int XetPrescribedMedication = 2131034170;
			
			// aapt resource value: 0x7f050038
			public const int XetRelationship = 2131034168;
			
			// aapt resource value: 0x7f05003e
			public const int XetState = 2131034174;
			
			// aapt resource value: 0x7f05003b
			public const int XetStreetAddress = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int XetZipOrPostcode = 2131034173;
			
			// aapt resource value: 0x7f050010
			public const int ZMCLabel = 2131034128;
			
			// aapt resource value: 0x7f05002e
			public const int btnDate = 2131034158;
			
			// aapt resource value: 0x7f050019
			public const int button1 = 2131034137;
			
			// aapt resource value: 0x7f050001
			public const int calendarView = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int courseInfoBtn = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int datePicker = 2131034127;
			
			// aapt resource value: 0x7f05002f
			public const int displayDateOfBirth = 2131034159;
			
			// aapt resource value: 0x7f050044
			public const int errormessageEdit = 2131034180;
			
			// aapt resource value: 0x7f050003
			public const int eventView = 2131034115;
			
			// aapt resource value: 0x7f05001a
			public const int gotoCalendarBtn = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int gotoContactBtn = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int gotoDonationsBtn = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int gotoProfileBtn = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int gotoSmsTestBtn = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int lgnEmail = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int lgnPassword = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int loginBtn = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int loginErrorOutput = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int loginProgressBar = 2131034135;
			
			// aapt resource value: 0x7f050043
			public const int nameEdit = 2131034179;
			
			// aapt resource value: 0x7f050022
			public const int prfDateOfBirth = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int prfEmail = 2131034150;
			
			// aapt resource value: 0x7f050020
			public const int prfFullName = 2131034144;
			
			// aapt resource value: 0x7f050028
			public const int prfGender = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int prfPhoneNumber = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int prfTextDateOfBirth = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int prfTextEmail = 2131034149;
			
			// aapt resource value: 0x7f05001f
			public const int prfTextFullName = 2131034143;
			
			// aapt resource value: 0x7f050027
			public const int prfTextGender = 2131034151;
			
			// aapt resource value: 0x7f050023
			public const int prfTextPhoneNumber = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int progressBar = 2131034153;
			
			// aapt resource value: 0x7f050018
			public const int registerBtn = 2131034136;
			
			// aapt resource value: 0x7f050041
			public const int registerProgressBar = 2131034177;
			
			// aapt resource value: 0x7f05002a
			public const int scrollView1 = 2131034154;
			
			// aapt resource value: 0x7f050045
			public const int sendButton = 2131034181;
			
			// aapt resource value: 0x7f050006
			public const int space1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int space2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int space3 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int space4 = 2131034124;
			
			// aapt resource value: 0x7f05002b
			public const int textRequiredFields = 2131034155;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int textView2 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textView3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView4 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView5 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView6 = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int txtDisplay = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int txtview1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int contact = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialogDate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int donations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int profile = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int registration = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int smsTest = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
