#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("zenmc.Resource", IsApplication=true)]

namespace zenmc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int EditText = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditTextError = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FormGroup = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002b
			public const int CPhone = 2131034155;
			
			// aapt resource value: 0x7f05005c
			public const int City = 2131034204;
			
			// aapt resource value: 0x7f050062
			public const int Country = 2131034210;
			
			// aapt resource value: 0x7f05002f
			public const int LoginEmail = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int LoginPassword = 2131034161;
			
			// aapt resource value: 0x7f050060
			public const int State = 2131034208;
			
			// aapt resource value: 0x7f05005a
			public const int Street = 2131034202;
			
			// aapt resource value: 0x7f050024
			public const int XbtnCancel = 2131034148;
			
			// aapt resource value: 0x7f050058
			public const int XbtnInsert = 2131034200;
			
			// aapt resource value: 0x7f050026
			public const int XerrorLog = 2131034150;
			
			// aapt resource value: 0x7f05001f
			public const int XetCity = 2131034143;
			
			// aapt resource value: 0x7f050040
			public const int XetConfirmPassword = 2131034176;
			
			// aapt resource value: 0x7f050019
			public const int XetContactName = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int XetContactPhoneNumber = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int XetCountry = 2131034146;
			
			// aapt resource value: 0x7f050012
			public const int XetEmail = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int XetFemale = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int XetFullName = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int XetGender = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int XetMale = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int XetMedicalConditions = 2131034140;
			
			// aapt resource value: 0x7f05003e
			public const int XetOldPassword = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int XetPassword = 2131034175;
			
			// aapt resource value: 0x7f050018
			public const int XetPhoneNumber = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int XetPrescribedMedication = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int XetRelationship = 2131034139;
			
			// aapt resource value: 0x7f050043
			public const int XetResetPassword = 2131034179;
			
			// aapt resource value: 0x7f05006b
			public const int XetSearchName = 2131034219;
			
			// aapt resource value: 0x7f050069
			public const int XetSelectEmail = 2131034217;
			
			// aapt resource value: 0x7f050067
			public const int XetSelectID = 2131034215;
			
			// aapt resource value: 0x7f050021
			public const int XetState = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int XetStreetAddress = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int XetZipOrPostcode = 2131034144;
			
			// aapt resource value: 0x7f05002e
			public const int ZMCLabel = 2131034158;
			
			// aapt resource value: 0x7f05005e
			public const int ZipOrPostcode = 2131034206;
			
			// aapt resource value: 0x7f05002d
			public const int btnBack = 2131034157;
			
			// aapt resource value: 0x7f050055
			public const int btnChangePassword = 2131034197;
			
			// aapt resource value: 0x7f050013
			public const int btnDate = 2131034131;
			
			// aapt resource value: 0x7f050057
			public const int btnEditProfile = 2131034199;
			
			// aapt resource value: 0x7f050053
			public const int btnEmergencyContact = 2131034195;
			
			// aapt resource value: 0x7f050056
			public const int btnMenu = 2131034198;
			
			// aapt resource value: 0x7f050037
			public const int btnResetPassword = 2131034167;
			
			// aapt resource value: 0x7f050054
			public const int btnResidentialAddress = 2131034196;
			
			// aapt resource value: 0x7f05006c
			public const int btnSearchName = 2131034220;
			
			// aapt resource value: 0x7f05006a
			public const int btnSelectEmail = 2131034218;
			
			// aapt resource value: 0x7f050068
			public const int btnSelectID = 2131034216;
			
			// aapt resource value: 0x7f050023
			public const int btnUpdate = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int cName = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int cRelationship = 2131034153;
			
			// aapt resource value: 0x7f050001
			public const int calendarView = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int courseInfoBtn = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int displayDateOfBirth = 2131034132;
			
			// aapt resource value: 0x7f050025
			public const int editProfileProgressBar = 2131034149;
			
			// aapt resource value: 0x7f05006f
			public const int errormessageEdit = 2131034223;
			
			// aapt resource value: 0x7f050003
			public const int eventView = 2131034115;
			
			// aapt resource value: 0x7f050038
			public const int gotoCalendarBtn = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int gotoContactBtn = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int gotoDonationsBtn = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int gotoLogOutBtn = 2131034173;
			
			// aapt resource value: 0x7f050039
			public const int gotoProfileBtn = 2131034169;
			
			// aapt resource value: 0x7f05003c
			public const int gotoSmsTestBtn = 2131034172;
			
			// aapt resource value: 0x7f050030
			public const int lgnEmail = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int lgnPassword = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int loginBtn = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int loginErrorOutput = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int loginProgressBar = 2131034165;
			
			// aapt resource value: 0x7f05006e
			public const int nameEdit = 2131034222;
			
			// aapt resource value: 0x7f050048
			public const int prfDateOfBirth = 2131034184;
			
			// aapt resource value: 0x7f05004c
			public const int prfEmail = 2131034188;
			
			// aapt resource value: 0x7f050046
			public const int prfFullName = 2131034182;
			
			// aapt resource value: 0x7f05004e
			public const int prfGender = 2131034190;
			
			// aapt resource value: 0x7f050050
			public const int prfMedical = 2131034192;
			
			// aapt resource value: 0x7f050052
			public const int prfMedication = 2131034194;
			
			// aapt resource value: 0x7f05004a
			public const int prfPhoneNumber = 2131034186;
			
			// aapt resource value: 0x7f050047
			public const int prfTextDateOfBirth = 2131034183;
			
			// aapt resource value: 0x7f05004b
			public const int prfTextEmail = 2131034187;
			
			// aapt resource value: 0x7f050045
			public const int prfTextFullName = 2131034181;
			
			// aapt resource value: 0x7f05004d
			public const int prfTextGender = 2131034189;
			
			// aapt resource value: 0x7f05004f
			public const int prfTextMedical = 2131034191;
			
			// aapt resource value: 0x7f050051
			public const int prfTextMedication = 2131034193;
			
			// aapt resource value: 0x7f050049
			public const int prfTextPhoneNumber = 2131034185;
			
			// aapt resource value: 0x7f050065
			public const int progressBar = 2131034213;
			
			// aapt resource value: 0x7f050036
			public const int registerBtn = 2131034166;
			
			// aapt resource value: 0x7f050059
			public const int registerProgressBar = 2131034201;
			
			// aapt resource value: 0x7f050041
			public const int resetPasswordProgressBar = 2131034177;
			
			// aapt resource value: 0x7f05000f
			public const int scrollView1 = 2131034127;
			
			// aapt resource value: 0x7f050066
			public const int searchLayout = 2131034214;
			
			// aapt resource value: 0x7f050070
			public const int sendButton = 2131034224;
			
			// aapt resource value: 0x7f050006
			public const int space1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int space2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int space3 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int space4 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int textRequiredFields = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int textView2 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textView3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView4 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView5 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView6 = 2131034126;
			
			// aapt resource value: 0x7f05005d
			public const int txtCity = 2131034205;
			
			// aapt resource value: 0x7f050028
			public const int txtContactName = 2131034152;
			
			// aapt resource value: 0x7f05002c
			public const int txtContactPhoneNumber = 2131034156;
			
			// aapt resource value: 0x7f050063
			public const int txtCountry = 2131034211;
			
			// aapt resource value: 0x7f050002
			public const int txtDisplay = 2131034114;
			
			// aapt resource value: 0x7f05006d
			public const int txtErrorLog = 2131034221;
			
			// aapt resource value: 0x7f050042
			public const int txtPasswordError = 2131034178;
			
			// aapt resource value: 0x7f05002a
			public const int txtRelationship = 2131034154;
			
			// aapt resource value: 0x7f050044
			public const int txtResetError = 2131034180;
			
			// aapt resource value: 0x7f050064
			public const int txtResultsLog = 2131034212;
			
			// aapt resource value: 0x7f050061
			public const int txtState = 2131034209;
			
			// aapt resource value: 0x7f05005b
			public const int txtStreetAddress = 2131034203;
			
			// aapt resource value: 0x7f05005f
			public const int txtZipOrPostcode = 2131034207;
			
			// aapt resource value: 0x7f050000
			public const int txtview1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int contact = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialogDate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int donations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int editProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int emergencyContact = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int passwordChange = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int passwordReset = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int profile = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int registration = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int residentialAddress = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int searchName = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int selectProfile = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int smsTest = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
